["Jakarta-Barat"]
name = "Jakarta Barat"
manager = "Budi"
counters = ["1", "2", "3"]
pricelist = [
    { type = "LM Certi (2026)",        price = 2_465_636, description = "LM Certi tahun 2026" },
    { type = "LM Certi (2024-2025)",   price = 2_325_636, description = "LM Certi tahun 2024 - 2025" },
    { type = "LM Certi (2021-2023)",   price = 2_305_636, description = "LM Certi tahun 2024 - 2025" },
    { type = "LM Certi (2018-2020)",   price = 2_295_636, description = "LM Certi tahun 2024 - 2025" },
    { type = "LM Retro",               price = 2_280_636, description = "LM Retro tahun 2015 ke atas" },
    { type = "UBS",                    price = 2_270_636, description = "UBS dengan logo terbaru" },
    { type = "Gold Bar (99,9%)",       price = 2_255_636 },
    { type = "Gold Bar (99%)",         price = 2_245_636 },
    { type = "K24 (99,9%)",            price = 2_245_636 },
    { type = "K24 (99%)",              price = 2_235_636 },
    { type = "K23",                    price = 1_949_000 },
    { type = "K22",                    price = 1_863_553 },
    { type = "K21",                    price = 1_780_141 },
    { type = "K20",                    price = 1_694_694 },
    { type = "K19",                    price = 1_609_248 },
    { type = "K18",                    price = 1_525_835 },
    { type = "K17",                    price = 1_440_388 },
    { type = "K16",                    price = 1_354_942 },
    { type = "K15",                    price = 1_271_529 },
    { type = "K14",                    price = 1_186_083 },
    { type = "K13",                    price = 1_100_636 },
    { type = "K12",                    price = 1_017_223 },
    { type = "K11",                    price = 931_777 },
    { type = "K10",                    price = 846_330 },
    { type = "K9",                     price = 762_918 },
    { type = "K8",                     price = 677_471 },
    { type = "K7",                     price = 592_024 },
    { type = "K6",                     price = 508_612 },
    { type = "K5",                     price = 423_165 },
    { type = "K4",                     price = 337_718 },
    { type = "K3",                     price = 254_306 },
    { type = "K2",                     price = 168_859 },
    { type = "Silver Ingot",           price = 29_435 },
    { type = "Silver High",            price = 25_230 },
    { type = "Silver Low",             price = 20_184 },
    { type = "Platinum High",          price = 702_661 },
    { type = "Platinum Low",           price = 562_129 },
    { type = "Palladium High",         price = 468_441 },
    { type = "Palladium Low",          price = 327_908 },
    { type = "Rhodium High",           price = 1_873_762 },
    { type = "Rhodium Low",            price = 1_733_230 },
    { type = "Iridium High",           price = 1_311_633 },
    { type = "Iridium Low",            price = 1_171_101 },
    { type = "Ruthenium High",         price = 120_000 },
    { type = "Ruthenium Low",          price = 102_000 },
    { type = "Tantalum",               price = 1_600_000 },
    { type = "Gold Material",          price = 2_375_636 },
    { type = "Silver Material",        price = 33_640 },
]


["Tanjung-Barat"]
name = "Tanjung Barat"
manager = "Sucipto"
counters = ["1", "2", "3"]
pricelist = [
    { type = "LM Certi (2026)",        price = 2_465_636, description = "LM Certi tahun 2026" },
    { type = "LM Certi (2024-2025)",   price = 2_325_636, description = "LM Certi tahun 2024 - 2025" },
    { type = "LM Certi (2021-2023)",   price = 2_305_636, description = "LM Certi tahun 2024 - 2025" },
    { type = "LM Certi (2018-2020)",   price = 2_295_636, description = "LM Certi tahun 2024 - 2025" },
    { type = "LM Retro",               price = 2_280_636, description = "LM Retro tahun 2015 ke atas" },
    { type = "UBS",                    price = 2_270_636, description = "UBS dengan logo terbaru" },
    { type = "Gold Bar (99,9%)",       price = 2_255_636 },
    { type = "Gold Bar (99%)",         price = 2_245_636 },
    { type = "K24 (99,9%)",            price = 2_245_636 },
    { type = "K24 (99%)",              price = 2_235_636 },
    { type = "K23",                    price = 1_949_000 },
    { type = "K22",                    price = 1_863_553 },
    { type = "K21",                    price = 1_780_141 },
    { type = "K20",                    price = 1_694_694 },
    { type = "K19",                    price = 1_609_248 },
    { type = "K18",                    price = 1_525_835 },
    { type = "K17",                    price = 1_440_388 },
    { type = "K16",                    price = 1_354_942 },
    { type = "K15",                    price = 1_271_529 },
    { type = "K14",                    price = 1_186_083 },
    { type = "K13",                    price = 1_100_636 },
    { type = "K12",                    price = 1_017_223 },
    { type = "K11",                    price = 931_777 },
    { type = "K10",                    price = 846_330 },
    { type = "K9",                     price = 762_918 },
    { type = "K8",                     price = 677_471 },
    { type = "K7",                     price = 592_024 },
    { type = "K6",                     price = 508_612 },
    { type = "K5",                     price = 423_165 },
    { type = "K4",                     price = 337_718 },
    { type = "K3",                     price = 254_306 },
    { type = "K2",                     price = 168_859 },
    { type = "Silver Ingot",           price = 29_435 },
    { type = "Silver High",            price = 25_230 },
    { type = "Silver Low",             price = 20_184 },
    { type = "Platinum High",          price = 702_661 },
    { type = "Platinum Low",           price = 562_129 },
    { type = "Palladium High",         price = 468_441 },
    { type = "Palladium Low",          price = 327_908 },
    { type = "Rhodium High",           price = 1_873_762 },
    { type = "Rhodium Low",            price = 1_733_230 },
    { type = "Iridium High",           price = 1_311_633 },
    { type = "Iridium Low",            price = 1_171_101 },
    { type = "Ruthenium High",         price = 120_000 },
    { type = "Ruthenium Low",          price = 102_000 },
    { type = "Tantalum",               price = 1_600_000 },
    { type = "Gold Material",          price = 2_375_636 },
    { type = "Silver Material",        price = 33_640 },
]


["Artha-Gading-Mall"]
name = "Artha Gading Mall"
manager = "Agus"
counters = ["1", "2", "3"]
pricelist = [
    { type = "LM Certi (2026)",        price = 2_465_636, description = "LM Certi tahun 2026" },
    { type = "LM Certi (2024-2025)",   price = 2_325_636, description = "LM Certi tahun 2024 - 2025" },
    { type = "LM Certi (2021-2023)",   price = 2_305_636, description = "LM Certi tahun 2024 - 2025" },
    { type = "LM Certi (2018-2020)",   price = 2_295_636, description = "LM Certi tahun 2024 - 2025" },
    { type = "LM Retro",               price = 2_280_636, description = "LM Retro tahun 2015 ke atas" },
    { type = "UBS",                    price = 2_270_636, description = "UBS dengan logo terbaru" },
    { type = "Gold Bar (99,9%)",       price = 2_255_636 },
    { type = "Gold Bar (99%)",         price = 2_245_636 },
    { type = "K24 (99,9%)",            price = 2_245_636 },
    { type = "K24 (99%)",              price = 2_235_636 },
    { type = "K23",                    price = 1_949_000 },
    { type = "K22",                    price = 1_863_553 },
    { type = "K21",                    price = 1_780_141 },
    { type = "K20",                    price = 1_694_694 },
    { type = "K19",                    price = 1_609_248 },
    { type = "K18",                    price = 1_525_835 },
    { type = "K17",                    price = 1_440_388 },
    { type = "K16",                    price = 1_354_942 },
    { type = "K15",                    price = 1_271_529 },
    { type = "K14",                    price = 1_186_083 },
    { type = "K13",                    price = 1_100_636 },
    { type = "K12",                    price = 1_017_223 },
    { type = "K11",                    price = 931_777 },
    { type = "K10",                    price = 846_330 },
    { type = "K9",                     price = 762_918 },
    { type = "K8",                     price = 677_471 },
    { type = "K7",                     price = 592_024 },
    { type = "K6",                     price = 508_612 },
    { type = "K5",                     price = 423_165 },
    { type = "K4",                     price = 337_718 },
    { type = "K3",                     price = 254_306 },
    { type = "K2",                     price = 168_859 },
    { type = "Silver Ingot",           price = 29_435 },
    { type = "Silver High",            price = 25_230 },
    { type = "Silver Low",             price = 20_184 },
    { type = "Platinum High",          price = 702_661 },
    { type = "Platinum Low",           price = 562_129 },
    { type = "Palladium High",         price = 468_441 },
    { type = "Palladium Low",          price = 327_908 },
    { type = "Rhodium High",           price = 1_873_762 },
    { type = "Rhodium Low",            price = 1_733_230 },
    { type = "Iridium High",           price = 1_311_633 },
    { type = "Iridium Low",            price = 1_171_101 },
    { type = "Ruthenium High",         price = 120_000 },
    { type = "Ruthenium Low",          price = 102_000 },
    { type = "Tantalum",               price = 1_600_000 },
    { type = "Gold Material",          price = 2_375_636 },
    { type = "Silver Material",        price = 33_640 },
]
